//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Sifre { get; set; }
        public string Email { get; set; }
        public int TcNo { get; set; }
        public int Telefon { get; set; }
        public string Adres { get; set; }
        public Nullable<bool> Statu { get; set; }
        public bool Silindi { get; set; }
    }
}
