//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Odemeler
    {
        public int id { get; set; }
        public int taksitsayisi { get; set; }
        public string banka { get; set; }
        public int cvcno { get; set; }
        public int kulid { get; set; }
    }
}
