//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Satislar
    {
        public int SatisNo { get; set; }
        public Nullable<int> KullaniciNo { get; set; }
        public Nullable<System.DateTime> SiparisTarih { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public Nullable<int> Miktar { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<long> Durumu { get; set; }
        public Nullable<bool> Silindi { get; set; }
        public Nullable<int> OdemeId { get; set; }
    }
}
