//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electro
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepeteEklenen
    {
        public int id { get; set; }
        public int SatisNo { get; set; }
        public int UrunId { get; set; }
        public Nullable<int> Adet { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public decimal Tutar { get; set; }
        public bool Satildi { get; set; }
        public string Detay { get; set; }
    }
}
