//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Electro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        public int Id { get; set; }
        public int KategoriId { get; set; }
        public int MarkaId { get; set; }
        public string Model { get; set; }
        public double Fiyat { get; set; }
        public string Detay { get; set; }
        public string Resim { get; set; }
        public bool Yeni { get; set; }
        public bool Ozel { get; set; }
        public bool Vitrin { get; set; }
        public bool Tavsiye { get; set; }
        public Nullable<int> Adet { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual Markalar Markalar { get; set; }
    }
}
